### ISSUE TITLE
小语法bug

### ISSUE THREAD

**Issue by AluminiumOxide** [anda522/anda522.github.io#52]
在[p/870124582.html](https://github.com/anda522/anda522.github.io/tree/master/p/870124582.html)中，
iota(beg, end) -> iota(beg, end, start)

**Comment by anda522** [comment]
> 在[p/870124582.html](https://github.com/anda522/anda522.github.io/tree/master/p/870124582.html)中， iota(beg, end) -> iota(beg, end, start)

收到，感谢。之后的线上发布版本就会修改上去了
